### ISSUE TITLE
Filtering Words

### ISSUE THREAD

**Issue by codeflawed** [Ewwmewgewd/FreezerBot#2]
Just had Chilly use the word rape in a random post. Is there anyway to have a word filter so that this doesn't happen?

**Comment by dexmoh** [comment]
Hey there, sorry for the long wait! The dataset Chilly was trained on was based on the chatlogs from the server where the bot is primarily used. I've tried filtering out the bad words, but it seems like one still snuck in. 

I haven't touched Chilly in a *short* while, but recently I've been working on completely rewriting him and improving/removing/adding some features. When that comes out (hopefully within next 2 weeks) I'll also make sure to filter out the r-word. Will close this issue when that happens!

**Comment by codeflawed** [comment]
Oh! Thank you for this. I had completely forgotten about it.
We've really been enjoying Chilly in our little server, so I'm glad to know
it's still being given love.

**Comment by dexmoh** [comment]
Glad you're liking Chilly ^^ I went through Chilly's chatbot data and hopefully removed most of the bad terminology! I've also reworked how his chatbot works so the sentences now might be a bit more random and nonsensical, I might work on this more in the future.

The new version is out, you can check it out [here](https://github.com/dexmoh/FreezerBotPy). You can DM me on discord (`dexmoh`) if there's anything else!
